User profile v2
acm-uic/registrum pull request #49
Opened 2020-03-29 06:01 UTC by jigar288

On the client side, I added the functionality to change user's password and account info using components from the react-bootstrap library and react hooks. On the back end, I wrote api routes to handle request for changing passwords and account info. The passwords were hashed using the bcrypt library. Review the code and let me know if there are necessary changes.

2020-03-29 11:01 UTC, alexchomiak requested changes
Clean up the code by implementing the recommendations I stated below. It can be done using less code.

2020-03-29 11:01 UTC, alexchomiak commented on client/src/pages/Account.tsx
> +    //* event handler to update password that will be trigger when user clicks submit
You should be checking Users' old password before making any changes, that way no one can commit any malicious activities. I'd add one more text field at the top that makes the user enter their old password, what we have now isn't the most secure.

2020-03-29 11:01 UTC, alexchomiak commented on api/src/routes/auth/index.ts
> +})
This can be all done in one route.

2020-03-29 11:01 UTC, alexchomiak commented on client/src/utils/functions/authentication.ts
> +
No need to abstract this out of the Page, if you change everything to a single route we circumvent a lot of redundant code.

2020-03-29 11:03 UTC, alexchomiak commented
Also, you should not be using the browser alert to notify the client of errors! Look at how we have done this in other files.

2020-03-29 11:05 UTC, alexchomiak commented on client/src/utils/functions/authentication.ts
> +            alert("Username updated successfully")
Change to use react-toastify

2020-03-29 11:05 UTC, alexchomiak commented on client/src/utils/functions/authentication.ts
> +            alert("Error updating username")
Change to use react-toastify

2020-03-29 11:05 UTC, alexchomiak commented on client/src/utils/functions/authentication.ts
> +            alert("Password updated successfully")
Change to use react-toastify

2020-03-29 11:05 UTC, alexchomiak commented on client/src/utils/functions/authentication.ts
> +            alert("Error updating password")
Change to use react-toastify

2020-03-29 11:05 UTC, alexchomiak commented on client/src/pages/Account.tsx
> +            alert("The two password fields don't match");
Change to use react-toastify

2020-03-29 19:35 UTC, clarkchentw submitted a review, later dismissed

2020-03-29 19:35 UTC, clarkchentw commented on api/src/routes/auth/index.ts
> +})
I would recommend not having an endpoint for checkPassword(It also post vulnerability in both checkPassword and changePassword), instead, you should check password within update password, and require an additional parameter to pass in for oldPassword.

2020-03-29 19:53 UTC, anarmawala submitted a review, later dismissed
Overall the code is good. Just minor changes to streamline the code

2020-03-29 19:53 UTC, anarmawala commented on client/src/pages/Account.tsx
> +                </Form.Group>
Form Feedback can be implemented to make sure the old and new password match our requirements
- `required` and `pattern` attributes can be used

2020-03-29 19:53 UTC, anarmawala commented on client/src/pages/Account.tsx
> +            </Form>
Form Feedback can be implemented to make sure the old and new password match our requirements
- `required` and `pattern` attributes can be used

2020-03-29 19:53 UTC, anarmawala commented on client/src/pages/Account.tsx
> +            }
Use `validateStatus` with `axios` so it will only give errors when a network connection could not be made. Then 401 status can be checked with `response.status`

2020-03-29 22:41 UTC, anarmawala commented on client/src/pages/Account.tsx
> +        setLName('')
Shouldn't this be last otherwise all the values will be blank?

2020-03-30 03:18 UTC, alexchomiak approved these changes

2020-03-30 03:21 UTC, merged