🚚 🐛🔥 Streamline Overall Code (Mostly Back end)
acm-uic/registrum pull request #55
Opened 2020-03-31 07:55 UTC by anarmawala

🚚 Moved values to the proper functions
🚚 Moved Regex to global
🐛 Fix Regex for name
🔥 Removed redundant/vulnerable `console.log` statements
💥 Change Testing port to 8085 to stop conflicting with `mongo-express` and `redis-commander` and `nginx`

2020-03-31 15:37 UTC, alexchomiak commented on api/src/routes/auth/index.ts
> +        // * Makes sure unnecessary keys/values are not sent
Delete what you don't want to send, don't specify each thing you are sending. It is less scalable that way. Just incase we want to update other attributes using this route later down the road.

2020-03-31 15:38 UTC, alexchomiak requested changes
Please make the change in regards to the comment I made. Otherwise everything looks good! Great job! 👍  🌮

2020-03-31 20:57 UTC, anarmawala commented on api/src/routes/auth/index.ts
> +        // * Makes sure unnecessary keys/values are not sent
Good point, changed in 1b725afba1c7ed6ffdcbf95c4a202822c0821f20. 🎉

2020-04-01 01:33 UTC, bmiddha requested changes

2020-04-01 01:33 UTC, bmiddha commented on .vscode/settings.json
> +    "cSpell.words": [
remove this from project config

2020-04-01 01:33 UTC, bmiddha commented on api/src/tests/auth.test.ts
> +                email: 'jimmy@registrum.app',
use example.com. They were specifically created by IANA to be used as example domains.

2020-04-01 01:33 UTC, bmiddha commented on api/src/tests/auth.test.ts
> +                email: 'jimmy@registrum.app',
use example.com. They were specifically created by IANA to be used as example domains.

2020-04-01 01:33 UTC, bmiddha commented on api/src/tests/banner.test.ts
> +            email: 'example@registrum.app',
use example.com. They were specifically created by IANA to be used as example domains.

2020-04-01 01:33 UTC, bmiddha commented on api/src/tests/banner.test.ts
> +            email: 'example@registrum.app',
use example.com. They were specifically created by IANA to be used as example domains.

2020-04-01 01:33 UTC, bmiddha commented on api/src/tests/class.test.ts
> +            email: 'example@registrum.app',
use example.com. They were specifically created by IANA to be used as example domains.

2020-04-01 01:41 UTC, anarmawala commented on api/src/tests/class.test.ts
> +            email: 'example@registrum.app',
Changed in f3631033ac6f5822cec92443b9135e97b69f5608

2020-04-01 01:41 UTC, anarmawala commented on api/src/tests/banner.test.ts
> +            email: 'example@registrum.app',
Changed in f3631033ac6f5822cec92443b9135e97b69f5608

2020-04-01 01:42 UTC, anarmawala commented on api/src/tests/auth.test.ts
> +                email: 'jimmy@registrum.app',
Changed in f3631033ac6f5822cec92443b9135e97b69f5608

2020-04-01 01:42 UTC, anarmawala commented on api/src/tests/banner.test.ts
> +            email: 'example@registrum.app',
Changed in f3631033ac6f5822cec92443b9135e97b69f5608

2020-04-01 01:42 UTC, anarmawala commented on api/src/tests/auth.test.ts
> +                email: 'jimmy@registrum.app',
Changed in f3631033ac6f5822cec92443b9135e97b69f5608

2020-04-01 01:43 UTC, anarmawala commented on .vscode/settings.json
> +    "cSpell.words": [
Removed in 7255e0681e1009505f01beeedf19d0b169da3da9

2020-04-01 01:48 UTC, bmiddha approved these changes
Looks good to me! 🎉 
🌮 Taco Tuesday! 🌮

2020-04-01 04:10 UTC, alexchomiak approved these changes

2020-04-01 04:11 UTC, alexchomiak commented
Thanks for making those changes! Everything looks good! 🎉 🌮

2020-04-01 17:06 UTC, merged