Push notifications v2
acm-uic/registrum pull request #70
Opened 2020-04-28 23:27 UTC by jigar288

Project now has PWA push notifications using service workers. Users will be notified when the classes they're tracking have seats available.

2020-04-29 00:27 UTC, bmiddha requested changes
Please remove the hard coded values from files.

2020-04-29 00:27 UTC, bmiddha commented on api/src/routes/push-service/index.ts
> +        webpush.setGCMAPIKey('565395438650')
Clean hard coded values

2020-04-29 00:27 UTC, bmiddha commented on api/src/routes/push-service/index.ts
> +            webpush.sendNotification(element, 'CRN:' + '44033' + ' ' + 'OPEN')
clean hard coded values

2020-04-29 00:27 UTC, bmiddha commented on api/src/util/notifier.ts
> +            'mailto:jigar@novusclub.org',
clean hard coded values

2020-04-29 00:27 UTC, bmiddha commented on client/package.json
> +        "prettier": "^2.0.5"
should be a dev dependency

2020-04-29 00:27 UTC, bmiddha commented on client/package.json
> +        "@types/react-select": "~3.0.11",
should be a dev dependency

2020-04-29 00:27 UTC, bmiddha commented on client/public/manifest.json
> +    "gcm_sender_id": "565395438650"
does this need to be hard coded here?

2020-04-29 00:27 UTC, bmiddha commented on client/public/service-worker.js
> +//TODO: add active, install, and push eventListeners
resolve todo comments

2020-04-29 00:27 UTC, bmiddha commented on client/src/index.tsx
> +// import * as serviceWorker from './serviceWorker'
remove the commented out service worker import and register

2020-04-29 00:27 UTC, bmiddha commented on client/src/serviceWorker.ts
> +    'BK_0D9VS_RrjJh3BRbdBifq6Ump45KpzfwWxk6P6sVOSTcrc89TzWlgtM1f7R7hOiKQsOxZHlGNGRiex02n9-9g'
hard coded key

2020-04-29 04:53 UTC, anarmawala requested changes
Good job 🌮! Left some comments

2020-04-29 04:53 UTC, anarmawala commented on api/src/routes/auth/index.ts
>          res.status(200).json(stripData(await User.findOne({ email: req.body.email })))
Change this line to not call `User.findOne` twice

2020-04-29 04:53 UTC, anarmawala commented on api/src/routes/push-service/index.ts
> +            'xRRruVND4fgEeBQoa3mld2ulOwXZxLtWAlaUyPuycpg'
These values should go into the ENV file

2020-04-29 04:53 UTC, anarmawala commented on api/src/routes/push-service/index.ts
> +            webpush.sendNotification(element, 'CRN:' + '44033' + ' ' + 'OPEN')
Does this verify that the class is actually open?

2020-04-29 04:53 UTC, anarmawala commented on client/public/service-worker.js
> +// TODO: this should only execute if user is logged in & tracking a class
Resolve TODO

2020-04-29 04:53 UTC, anarmawala commented on client/src/serviceWorker.ts
> +    // TODO: write some code that enables and disables button on the front end that subscribes user for push notifications
Resolve TODO

2020-04-29 04:53 UTC, anarmawala commented on client/src/serviceWorker.ts
> +    if ('serviceWorker' in navigator) {
This should be changed to **`'serviceWorker' in navigator && (process.env.NODE_ENV === production || isLocalhost)`**

2020-04-29 04:53 UTC, anarmawala commented on client/src/serviceWorker.ts
> +            let swUrl = `${process.env.PUBLIC_URL}/service-worker.js`
We can remove `${process.env.PUBLIC_URL}` completely

2020-04-29 06:40 UTC, alexchomiak approved these changes
Very well documented code, I see I'm starting to get to you Jigar 😉 As Bharat says I think it's adamant you remove the hardcoded variables and replace them with env variables that can be specified by the programmer hosting the application. Great work!

2020-04-30 03:05 UTC, jigar288 commented on client/public/manifest.json
> +    "gcm_sender_id": "565395438650"
doesn't need to be a hardcoded value and can't use .env variables in manifest.json public file

2020-04-30 03:16 UTC, jigar288 commented on api/src/routes/push-service/index.ts
> +            webpush.sendNotification(element, 'CRN:' + '44033' + ' ' + 'OPEN')
this route isn't actually used. Its for our testing purposes

2020-04-30 04:16 UTC, anarmawala requested changes
Two things, I noticed but otherwise the code looks great. Good Job 🌮 🎉

2020-04-30 04:16 UTC, anarmawala commented on client/src/serviceWorker.ts
> +        let swUrl = `./service-worker.js`
Change of `const`

2020-04-30 04:16 UTC, anarmawala commented on client/src/serviceWorker.ts
>      if ('serviceWorker' in navigator) {
Change `'serviceWorker' in navigator` to `'serviceWorker' in navigator && (process.env.NODE_ENV === 'production' || isLocalhost)`

2020-04-30 04:27 UTC, bmiddha approved these changes
Great job. 🌮

2020-04-30 04:28 UTC, anarmawala approved these changes
🌮

2020-04-30 23:30 UTC, merged